name: seqlib
channels:
  - conda-forge
  - defaults
  - r
  - bioconda
dependencies:
  - requests
  - click
  - ujson
  - coverage
  - pytest
  - pytest-cov
  - pytest-flake8
  - codecov
  - pip:
    - pytest-helpers-namespace

